desc "Rewrite index.html using index.erb and publisher_homepage.html"
task :index do
  require 'erb'
  @title = "Injection - atomicobject.rb"
  @plugin_install = "$ script/plugin install svn://rubyforge.org/var/svn/atomicobjectrb/tags/injection"
  @header_html = File.read("page_header.html")
  html = ERB.new(File.read("index.erb")).result(binding)
  fname = "index.html"
  File.open(fname,"w") do |f|
    f.print html
  end
  puts "Wrote #{fname}"
end

task :default => :index
